# arch linux 安装 mingw-w64-gcc
# rustup toolchain install stable-x86_64-pc-windows-gnu
# rustup target add x86_64-pc-windows-gnu --toolchain=stable

# rustup toolchain install stable-x86_64-pc-windows-msvc
# rustup target add x86_64-pc-windows-msvc --toolchain=stable

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
#ar = "/usr/x86_64-mingw32/bin/ar"
ar = "/usr/bin/x86_64-w64-mingw32-gcc-ar"

[target.x86_64-pc-windows-msvc]
linker = "/usr/bin/x86_64-w64-mingw32-vcc"
#ar = "/usr/x86_64-mingw32/bin/ar"
ar = "/usr/bin/x86_64-w64-mingw32-gcc-ar"
