env:
  LC_ALL: "en_US.UTF-8"

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  decorations: full
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 14.0
  offset:
    x: 0
    y: 2
  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: false

schemes:
  gruvbox_light: &light
    primary:
      hard contrast: background = '#f9f5d7'
      background: '#fbf1c7'
      soft contrast: background = '#f2e5bc'
      foreground: '#3c3836'
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

  gruvbox_dark: &dark
    primary:
      background: '#32302f'
      foreground: '#ebdbb2'
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

colors: *dark

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

opacity: 1.0

cursor:
  style:
    shape: Block
    blinking: Off
  vi_mode_style: None
  blink_interval: 750
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true

working_directory: None

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

hints:
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
   - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: Paste,                                       action: Paste          }
  - { key: Copy,                                        action: Copy           }
  - { key: L,         mods: Control,                    action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
