#!/usr/bin/env bash
SCRIPT_PATH="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd -P)"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPT_PATH/down /tmp/leftwm-theme-down

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPT_PATH/theme.toml"

# Scheduled rest
[ -f "$HOME/.local/bin/notify-rest.sh" ] && $HOME/.local/bin/notify-rest.sh >/tmp/notify-rest.log 2>&1 &
